server:
  port: '8088'

file:
  upload-dir: '[ckEditor에서 업로드하는 이미지가 저장될 경로를 지정해주세요.]'
  # 예시 : 'D:\github\wanted-pre-onboarding-backend\RecruitmentSite\src\main\resources\static\ckUploads\'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_site_db
    username: internship
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
#    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
